### PR TITLE
Merging geometric with yan

### PR DESCRIPTION
**Pull request by hyanwong**
This now passes all but 2 tests. One test fails because of an underflow/overflow error (`tests/test_inference.py:TestSimulated.test_simple_sim_larger_example`), the other because a hard coded test value probably needs updating. Otherwise, I think it can probably be merged into master, so that at least we have a geometric scaling algo there. What do you think, @awohns ?

### CODE REVIEW

**Comment by awohns** [comment]
This version overflows because it isn’t solely in log-space. I need to merge it with ‘full-log-geo-scale’ which I’ll do tomorrow. Sorry!

**Comment by hyanwong** [comment]
Yes, I guessed that was the problem. Happy to wait for your update. I hope it's not too difficult to merge all these together. It would be useful for us all to be working from the same Master branch, I think.

**Comment by hyanwong** [comment]
Did you manage to merge with the log-geoscale branch, @awohns ?

**Comment by awohns** [comment]
I’m working on it, there are a few tests that don’t pass because everyone is kept “logged” all the time and require some fiddly and tedious reworking unfortunately...

**Comment by hyanwong** [comment]
No hurry. I was just wondering.

**Pull request closed without merging**
