### PR TITLE
Parallel poisson pmf

### PR DESCRIPTION
**Pull request by hyanwong**
For reference as an implementation of multiprocessing

### CODE REVIEW

**Comment by hyanwong** [comment]
This should be perf tested, as (because the `get_ll` function is reasonably fast, but gets called millions of times) it may be that the overhead of pickling the function outweighs the benefit from parallelisation. I don't understand well enough the way multiprocessing works (especially with functools.partial) to know if we will see a substantial increase in speed or not, but I'm hopeful...

**Comment by hyanwong** [comment]
Premature optimisation and all that, but I suspect that my recent implementation using a set (`result ={...}`) will be just as slow, as there will be hash collisions when making the set, rather than making the dictionary. 

Perhaps better would be to put the number of mutations and span into a basic numpy [structured array](https://docs.scipy.org/doc/numpy/user/basics.rec.html) and use np.unique to find the keys for the `result` array.

**Comment by awohns** [comment]
It's unclear to me if this is actually speeding up the pmf calculation... preliminary testing shows that using num_threads=5 is often slower than the single threaded version

**Comment by hyanwong** [comment]
Done as part of https://github.com/awohns/tsdate/pull/77

**Pull request closed without merging**
